apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-deno-boilerplate-operator-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-deno-boilerplate-controller
rules:
  - apiGroups: ["k8s.evertdespiegeleer.com"]
    resources: ["greetings"]
    verbs: ["*"]
  - apiGroups: ["k8s.evertdespiegeleer.com"]
    resources: ["greetings/status"]
    verbs: ["*"]
  # Make sure any resources you need access to are specified here
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-deno-boilerplate-operator-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: k8s-deno-boilerplate-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: k8s-deno-boilerplate-operator-sa
    namespace: {{ .Release.Namespace }}
